handle    = "Bob"
port      = [5012, 5012]     # Port-Range von 5012 bis 5012 (Einzel-Port)
whoisport = 4000
autoreply = "Bin gerade nicht da."
imagepath = "images"         # oder "./images", beides geht

[colors]
Alice    = "RED"
Bob      = "GREEN"
Caroline = "BLUE"
Diana    = "MAGENTA"


#bash im Terminal von Bob, um ihr Chat zu straten:

#rm -f /tmp/chat_discovery_7000.lock
#python3 discovery_main.py bob.toml 7000 > logs/bob.discovery.log 2>&1 & sleep 0.2
#python3 network_main.py   bob.toml 7001 > logs/bob.network.log   2>&1 & sleep 0.2
#python3 main_ui.py        bob.toml 7000 7001


