handle    = "Caroline"
port      = [5013, 5013]     # Port-Range von 5013 bis 5013 (Einzel-Port)
whoisport = 4000
autoreply = "Bin gerade nicht da."
imagepath = "images"         # oder "./images", beides geht