handle    = "caroline"
port      = [5013, 5013]     # lokaler UDP-Port 5013
whoisport = 4000             # Discovery‐Port
autoreply = "Bin gerade nicht da."
imagepath = "images"         # Ordner für empfangene Bilder
